#! /bin/bash

function create {
    DIR="$( pwd )"
    pushd $DIR

    echo "What is the name of the new role?"
    read role_name

    if [ -n "$role_name" ]; then
        role_name_dir="$(echo "$role_name" | sed 's/ /_/g')"

        mkdir -p roles/$role_name_dir
        pushd roles/$role_name_dir

        mkdir task
        pushd task
        echo "---" > main.yml      
        echo "# Tasks file can include smaller files if warranted" >> main.yml
        popd

        mkdir handlers
        pushd handlers
        echo "---" > main.yml      
        echo "# Handlers for $role_name" >> main.yml
        popd
        
        mkdir templates
        pushd templates
        echo "Files for use with the template resource" > README.md
        echo "ntp.conf.j2   <------- templates end in .j2" >> README.md
        popd
        
        mkdir files
        pushd files
        echo "bar.txt  <-- files for use with the copy resource" > README.md
        echo "foo.sh   <-- script files for use with the script resource" >> README.md
        popd
        
        mkdir vars
        pushd vars
        echo "---" > main.yml
        echo "# Variables associated with the $role_name role" >> main.yml
        popd
        
        mkdir defaults
        pushd defaults
        echo "---" > main.yml      
        echo "# Default lower priority variables for the $role_name role" >> main.yml
        popd
        
        mkdir meta
        pushd meta
        echo "---" > main.yml
        echo "# $role_name role dependencies" >> main.yml
        popd
        
        mkdir library
        pushd library
        echo "# Custom modules for the $role_name role" > README.md
        popd
        
        mkdir module_utils
        pushd module_utils 
        echo "# Custom module utilities for the $role_name role" > README.md
        popd
        
        mkdir lookup_plugins
        pushd lookup_plugins
        echo "# Other types of plugins, like lookup in this case" > README.md
        popd

        popd
    fi

    popd    
}

$@
