#! /bin/bash

function new {

    echo "What is the name of the host?"
    read host_name

    if ( "$host_name" == "" ); then
        exit
    else
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

        host_name_dir = sed -r 's/ /_/g'

        mkdir -p $DIR/host_vars/$host_name_dir
        pushd $DIR/host_vars/$host_name_dir
        echo "Default variables for ${host_name} host" > README.md
        echo "---" > main.yml
        popd
    fi
}
